### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by clue** [bixuehujin/reactphp-mysql#12]
Hi @bixuehujin, I'd like to let you know I very much like your project and would love to also start working on this :+1: 

However, the current license situation makes this a bit unclear to me.

Can your code be released under the MIT license? If so, this should be a matter of dumping a `LICENSE` file (for example https://github.com/clue/php-buzz-react/blob/master/LICENSE) in the project root and updating the `composer.json` accordingly.

Thanks!

**Comment by bixuehujin** [comment]
MIT license looks good to me~
