### ISSUE TITLE
react/mysql hard-depends on old react/socket version

### ISSUE THREAD

**Issue by guss77** [bixuehujin/reactphp-mysql#20]
Because react/mysql depends on a specific old minor version of react/socket (0.4), its not possible to use it in projects that depend on libraries (such as react/http) that require a more recent version of react/socket.

I suggest changing the requirement for react/socket and react/socket-client to support upgrades as needed.

Thanks.

**Comment by icekingcy** [comment]
+1. Same with you.

**Comment by Fneufneu** [comment]
i made #21 to update the code to the last version of react/socket if you want.
