### ISSUE TITLE
Frontend display

### ISSUE THREAD

**Issue by vbezruchkin** [bixuehujin/reactphp-mysql#7]
Greetings guys,

Looks interesting, thanks.
One question though, how do we display the result records on frontend? I do understand the fetch flow for mysql queries but is there any simply way to update frontend table with the new records? So I don't do ajax requests and see the updated stuff immediately once the record is updated. Should php somehow trigger the html update, shouldn't it?

Please clarify. Thanks in advance!

**Comment by bixuehujin** [comment]
Push technologies such as WebSocket and long polling may fit your needs,  but it's more complicated than ajax, i don't think it's worth for it.

**Comment by vbezruchkin** [comment]
Thanks for your advice.
